/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://rx3eo36razdetcaleejsya2wdm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7vd6wcfyirgvrldk2o5llaoxmi",
    "aws_cognito_identity_pool_id": "us-west-2:6027b6c8-329f-4bed-89f0-bce72263cc60",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pJpQscaLg",
    "aws_user_pools_web_client_id": "7ouuru90s1msfb4e0lghpk371f",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "blogamplifytest-20220202170851-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://blogamplifytest-20220202170851-hostingbucket-dev.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
